version: '3.1'

networks:
  mirea-network:
    external: false

services:
  http-node-server:
    image: http-node-server:latest
    hostname: http-node-server
    restart: "no"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./index.js:/app/index.js:ro
      - ./settings.json:/app/settings.json:ro
      - ./src:/app/src:ro
    ports:
      - "25665:25665"
    networks:
      - mirea-network
    depends_on:
      - mongodb

  mongodb:
    image: mongo:4.4.6
    hostname: mongodb
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./mongodb:/data/db:rw
    ports:
      - "127.0.0.1:27018:27017"
    networks:
      - mirea-network